  
version: '3'
services:
  #app:
    #container_name: node
    #build: .
    #ports:
     # - '3000:3000'
    #external_links:
     # - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './db:/docker-entrypoint-initdb.d'
      - './mongobase:/data/db'
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: hola
      MONGO_INITDB_DATABASE: paik
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#     ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: hola
    depends_on:
      - mongo
